// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efaasxatkeswqhufuktp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmYWFzeGF0a2Vzd3FodWZ1a3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTE5NjAsImV4cCI6MjA3NDcyNzk2MH0.VTgYYV4urDXV-jZ0Fk1pKQ4CYNhTRfF2b9PT3SkEDVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});